[tool.poetry]
name = "hll-server-status"
version = "1.1.0"
description = "A server status tool for reporting Hell Let Loose server status to Discord"
authors = ["C. Eric Mathey <emathey@protonmail.com>"]
readme = "README.md"
packages = [{ include = "hll_server_status" }]

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.1.0"
nox = "^2022.11.21"
pydantic = "^1.10.4"
python-dateutil = "^2.8.2"
tomlkit = "^0.11.6"
mypy = "^0.991"
trio = "^0.22.0"
requests = "^2.28.2"
httpx = "^0.23.3"
loguru = "^0.6.0"

[tool.poetry.group.dev.dependencies]
loguru-mypy = "^0.0.4"
black = "^23.1.0"
isort = "^5.12.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
